runtime: go116
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
  - url: .*
    script: auto
env_variables:
  DATABASE_URL: postgres://postgres:postgres@35.223.54.178:5432/fitstackapi_development?sslmode=disable
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: fitstack-343223@appspot.gserviceaccount.com